/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionCapture: typeof import('./src/pages/ActionCapture.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    Model: typeof import('./src/pages/Model.vue')['default']
    ModelLibrary: typeof import('./src/pages/ModelLibrary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/pages/Settings.vue')['default']
    SvgIcon: typeof import('./src/components/common/SvgIcon.vue')['default']
  }
}
