/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionCapture: (typeof import('./src/pages/ActionCapture.vue'))['default']
    Knob: (typeof import('./src/components/common/form/Knob.vue'))['default']
    MainLayout: (typeof import('./src/components/layout/MainLayout.vue'))['default']
    Model: (typeof import('./src/pages/Model.vue'))['default']
    ModelLibrary: (typeof import('./src/pages/ModelLibrary.vue'))['default']
    PrAccordion: (typeof import('primevue/accordion'))['default']
    PrAccordionTab: (typeof import('primevue/accordiontab'))['default']
    PrButton: (typeof import('primevue/button'))['default']
    PrDropdown: (typeof import('primevue/dropdown'))['default']
    PrFileUpload: (typeof import('primevue/fileupload'))['default']
    PrKnob: (typeof import('primevue/knob'))['default']
    PrMenubar: (typeof import('primevue/menubar'))['default']
    PrProgressSpinner: (typeof import('primevue/progressspinner'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    Settings: (typeof import('./src/pages/Settings.vue'))['default']
    SvgIcon: (typeof import('./src/components/common/SvgIcon.vue'))['default']
  }
}
